# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Program PDF"
  url = "project/full-program/program.pdf"
  weight = 20

[[main]]
  name = "Program"
  url = "#talks"
  weight = 30

#[[main]]
#  name = "Topics"
#  url = "#tags"
#  weight = 25

#[[main]]
#  name = "Participants"
#  url = "#people"
#  weight = 40


[[main]]
  name = "Organizers"
  url = "#chairs"
  weight = 45


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

#[[main]]
#  name = "FR"
#  url = "#"
#  weight = 65

